app/web/routes.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for
from flask_login import current_user, logout_user, login_required

web = Blueprint('web', __name__)

@web.route('/')
def home():
	return render_template('sample.html')

@web.route("/login", methods=['GET'])
def login():
	next_page = request.args.get('next')
	if current_user.is_authenticated:
		return redirect(next_page) if next_page else redirect(url_for('web.dashboard'))
	return render_template('signin.html', title="Login")

@web.route("/logout")
def logout():
	if not current_user.is_authenticated:
		return redirect(url_for('web.login'))
	logout_user()
	return redirect(url_for('web.login'))

@web.route("/dashboard")
@login_required
def dashboard():
	# redirect users to their own dashboard based on their role
	if current_user.role == 'patient':
		return redirect(url_for('web.patient_dashboard'))
	elif current_user.role == 'doctor':
		return redirect(url_for('web.doctor_dashboard'))
	elif current_user.role == 'super_admin':
		return redirect(url_for('web.admin_dashboard'))
	return redirect(url_for('web.home'))

@web.route("/dashboard/admin")
@login_required
def admin_dashboard():
	"""This is for admin"""
	return render_template('adminpanel.html', title="Admin Panel")

@web.route("/dashboard/doctor")
@login_required
def doctor_dashboard():
	"""This is for doctor"""
	return render_template('doctor-dashboard.html', title="Doctor Dashboard")

@web.route("/dashboard/patient")
@login_required
def patient_dashboard():
	"""This is for patient"""
	return render_template('patient-dashboard.html', title="Patient Dashboard")

app/templates/layouts/base.html
<!DOCTYPE html>
<html>

<head>
	<meta name="google" content="notranslate" />
	<meta charset="UTF-8">

	<!-- GSAP Animation tools -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.4.2/gsap.min.js"></script>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<!-- common source files -->
	<script src="{{ url_for('static', filename='js/utils.js') }}"></script>
	<script src="{{ url_for('static', filename='js/basics.js') }}"></script>
	<script src="{{ url_for('static', filename='js/api_calls.js') }}"></script>

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/basics.css') }}">

	{% block header_scripts %}

	{% endblock header_scripts %}

	{% if title %}
	<title>{{ title }} - Glaxoderma</title>
	{% else %}
	<title>Glaxoderma</title>
	{% endif %}

</head>

<body>

	<div class="container" id="container">
		<!--Right Side Bar-->

		<!--Top Floting Offer-->
		<!-- div>
			<div id="top-floating-offer">
				<p id="top-floating-offer-text">20% Product Offer</p>
			</div>
			<div id="top-floating-close" style="position: fixed;margin-left: 90vw;z-index: 2;font-size: 30px">
				<i class="fa fa-window-close" aria-hidden="true"></i>
			</div>
		</div> -->
		<div id="top-notification">
	    	<div id="top-notification-close" style="float: right; padding-right: 10px"><i class="fa fa-window-close"></i></div>
	    	<div id="top-notification-data">স্বাগতম গ্লাক্সোডার্মাতে!!</div>
	    </div>

		<div id="header">
			<div id="header-canvas-container">
				<canvas id="header-canvas"></canvas>
				<div id="logo">
					<div id="logo-text">GLAXODERMA</div>
					<img id="logo-img" src="{{ url_for('static', filename='images/Glaxoderma_logo.png') }}">
					<img id="logo-grad" src="{{ url_for('static', filename='images/gradient.png') }}">
				</div>
			</div>
			<div id="header-bar" class="row">
				<div id="col-1" class="col-12 col-md-8">
		            <a href="{{ url_for('web.home') }}" type="button" class="btn nav-btn-ctm">
		                <div class="english-static">HOME</div>
		                <div class="bangla-static">হোম</div>
		            </a>
		            <a href="products.html" type="button" class="btn nav-btn-ctm">
		                <div class="english-static">PRODUCTS</div>
		                <div class="bangla-static">পন্য</div>
		            </a>
		            <a href="specialists.html" type="button" class="btn nav-btn-ctm">
		                <div class="english-static">SPECIALISTS</div>
		                <div class="bangla-static">বিশেষজ্ঞ</div>
		            </a>
		            <a href="services.html" type="button" class="btn nav-btn-ctm">
		                <div class="english-static">SERVICES</div>
		                <div class="bangla-static">সেবা</div>
		            </a>
		            <a href="#" type="button" class="btn nav-btn-ctm">
		                <div class="english-static">ABOUT US</div>
		                <div class="bangla-static">আমাদের সম্পর্কে</div>
		            </a>
		            <div style="display: inline-block">
		                <div style="display: inline-block;padding-left: 20px;margin:0px;margin-top: 10px;">
		                    <div class="english-static">Language</div>
		                    <div class="bangla-static">ভাষা</div>
		                </div>
		                <div class="dropdown" id="lang-dropdown" style="display: inline-block;margin:0px;margin-top: 10px;">
		                  <button class="btn btn-secondary dropdown-toggle" type="button" id="lang-dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		                    <div class="english-static">English</div>
		                    <div class="bangla-static">বাংলা</div>
		                  </button>
		                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		                    <a type="button" class="dropdown-item lang-dropdown-item">English</a>
		                    <a type="button" class="dropdown-item lang-dropdown-item">বাংলা</a>
		                  </div>
		                </div>
		            </div>
		        </div>
		        <!-- <div id="nav-bar-user-info" class="col-12 col-md-4" >
		            <a href="signin.html" type="button" id="login-btn" class="btn nav-btn-ctm security-info-btn">
		                <div id="login-text">
		                    <div class="english-static">Login</div>
		                    <div class="bangla-static">প্রবেশ করুন</div>
		                </div>
		                <div id="logout-text"  style="display: none">
		                    <div class="english-static">Logout</div>
		                    <div class="bangla-static">প্রস্থান</div>
		                </div>
		            </a>
		            <a href="adminpanel.html" type="button" id="admin-panel-btn" class="btn nav-btn-ctm security-info-btn">
		                ADMIN
		            </a>
		        </div> -->

				<!-- <div class="col-12 col-md-8">
					<a href="{{ url_for('web.home') }}" type="button" class="btn nav-btn-ctm">HOME</a>
					<a href="#" type="button" class="btn nav-btn-ctm">PRODUCTS</a>
					<a href="#" type="button" class="btn nav-btn-ctm">SERVICES</a>
					<a href="#" type="button" class="btn nav-btn-ctm">ABOUT US</a>
				</div>-->
				<div class="col-12 col-md-4">
					{% if current_user.is_authenticated %}
						<a href="{{ url_for('web.logout') }}" type="button" class="btn nav-btn-ctm security-info-btn">
							<div id="logout-text">
			                    <div class="english-static">Logout</div>
			                    <div class="bangla-static">প্রস্থান</div>
			                </div>
            			</a>
						<a href="{{ url_for('web.dashboard') }}" type="button" class="btn nav-btn-ctm security-info-btn">Dashboard</a>
					{% else %}
						<a href="{{ url_for('web.login') }}" type="button" class="btn nav-btn-ctm security-info-btn">
							<div id="login-text">
			                    <div class="english-static">Login</div>
			                    <div class="bangla-static">প্রবেশ করুন</div>
			                </div>
		                </a>
					{% endif %}
				</div> 
			</div>
		</div>

	{% block content %}

	{% endblock content %}

	<div id="footer-container">
		{% include('components/footer_main.html') %}
	</div>
</div>

	

	<!-- Bootstrap JS  -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

	{% block footer_scripts %}

	{% endblock footer_scripts %}

</body>

</html>